import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { ClerkProvider } from '@clerk/nextjs'

import Footer from '@/components/shared/Footer'
import Navbar from '@/components/shared/Navbar'
import Leftbar from '@/components/shared/Leftbar'
import Rightbar from '@/components/shared/Rightbar'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>
        <Navbar/>

        <main>
          <Leftbar/>

          <section className='main-container'>
            <div className='w-full max-w-4xl'>
            {children}

            </div>
          </section>

          <Rightbar/>

        </main>
        <Footer/>
        
       
        </body>
    </html>
    </ClerkProvider>
  )
}
